export const LOGIN = '/api/v1/login'
export const REFRESH_SESSION = '/api/v1/refreshSession'
export const ALL_ITEM = '/api/v1/allItems'
export const ALL_MENU = '/api/v1/allMenus'
export const ITEM = '/api/v1/items'
export const MENU = '/api/v1/menus'